### ISSUE TITLE
Fix head rotation

### ISSUE THREAD

**Issue by DrkMatr1984** [ClassicTowny/follow#1]
Add an Option or perhaps make it default to fix the head rotation when following.

**Comment by 008** [comment]
i think its not posible, if i updating move ivent every 0.1 sec its still very laggy

**Comment by DrkMatr1984** [comment]
OK. I will try anyway. If I have success I will upload source and jar.

**Comment by 008** [comment]
just friendly reminder ^)

**Comment by 008** [comment]
any ideas ?

**Comment by 008** [comment]
16 days...

**Comment by DrkMatr1984** [comment]
Sorry man, I'll have a look tonight. It hasn't been on the top of my priority list as I'm not currently using this plugin. But I'll see what I can do.

**Comment by DrkMatr1984** [comment]
Try this Build:
https://github.com/ClassicTowny/follow/releases/tag/Follow-0.7-beta1
You'll have to enable "rotateHead: true" in config, but it's working for me :)
( I also have significantDistance: 0.15 in my config)

**Comment by DrkMatr1984** [comment]
Does it work for you?

**Comment by 008** [comment]
laggs as hell - video https://youtu.be/gdkJBmLWQf4

**Comment by DrkMatr1984** [comment]
Yeah, it's not actually lagging. It's just that it teleports the person whose head is rotating to rotate them rather than rotating them directly so the camera effect looks jittery. Let me see if there's a way for me to rotate the player without teleporting them.

Edit: I found a way to do it using packets and/or NMS, but it will take a while to code. I suggest using the latest release I'm about to release until I add the Packet method. (Trick client into thinking in spectator mode)

**Comment by DrkMatr1984** [comment]
Im going to add a commit soon that while following, follow puts the Player in spectator mode viewing the Player.  The Player will still teleport like before and appear to follow the other Player when viewed from others,  but the Player actually using the follow command will see everything in spectator mode. I may add options that knock you out of follow and spectator mode if you take damage or press a certain key.

**Comment by DrkMatr1984** [comment]
Leaving default for now. I may code a better Follow plugin later.
